/**
 * Document definitions for the AI Career Studio downloads. Each builder
 * turns saved, candidate-confirmed data into the plain document model the
 * renderer understands. Builders only ever read data — they never call a
 * model or add content that is not already saved.
 */

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function formatMonth(value = '') {
  const m = String(value).match(/^(\d{4})(?:-(\d{2}))?/);
  if (!m) return String(value || '');
  return m[2] ? `${MONTHS[Number(m[2]) - 1] || ''} ${m[1]}`.trim() : m[1];
}

const range = (start, end, current) => [formatMonth(start), current ? 'Present' : formatMonth(end)].filter(Boolean).join(' – ');
const list = (a) => (Array.isArray(a) ? a.filter(Boolean) : []);
const allSkills = (skills = {}) => Array.from(new Set(Object.values(skills).flat().filter(Boolean)));

function contactLines(p = {}) {
  return [
    p.headline,
    [p.location, p.email, p.phone].filter(Boolean).join('  •  '),
    [p.linkedin, p.website].filter(Boolean).join('  •  '),
  ];
}

const experienceBlocks = (resume) =>
  list(resume.experience).map((r) => ({
    type: 'entry',
    title: [r.title, r.company].filter(Boolean).join(' — '),
    subtitle: [range(r.startDate, r.endDate, r.current), r.location].filter(Boolean).join('   |   '),
    bullets: [...list(r.responsibilities), ...list(r.achievements)],
  }));

const educationBlocks = (resume) =>
  list(resume.education).map((e) => ({
    type: 'entry',
    title: [e.degree, e.field].filter(Boolean).join(', ') || e.institution,
    subtitle: [e.degree || e.field ? e.institution : '', range(e.startDate, e.endDate), e.grade].filter(Boolean).join('   |   '),
    bullets: list(e.highlights),
  }));

const certificationItems = (resume) =>
  list(resume.certifications).map((c) => [c.name, c.issuer, formatMonth(c.issueDate)].filter(Boolean).join(' — '));

const projectBlocks = (resume) =>
  list(resume.projects).map((p) => ({
    type: 'entry',
    title: p.name,
    subtitle: [p.role, range(p.startDate, p.endDate), p.link].filter(Boolean).join('   |   '),
    text: p.description,
    bullets: p.technologies?.length ? [`Technologies: ${p.technologies.join(', ')}`] : [],
  }));

const languageItems = (resume) =>
  list(resume.languages).map((l) => (typeof l === 'string' ? l : [l.name, l.proficiency && `(${l.proficiency})`].filter(Boolean).join(' ')));

/**
 * LinkedIn-style profile document, in LinkedIn's section order. It is a
 * DutyLaunch document built from confirmed data — not a LinkedIn export,
 * and it says so on every page.
 */
export function profileDocument(resume) {
  const p = resume.personal || {};
  return {
    title: `${p.name || 'Candidate'} — Professional Profile`,
    subject: 'Professional profile generated by DutyLaunch from candidate-confirmed information',
    header: { name: p.name, lines: contactLines(p) },
    footerNote: 'Generated by DutyLaunch from candidate-confirmed information. Not an official LinkedIn document.',
    sections: [
      { heading: 'About', blocks: resume.summary ? [{ type: 'paragraph', text: resume.summary }] : [] },
      { heading: 'Experience', blocks: experienceBlocks(resume) },
      { heading: 'Education', blocks: educationBlocks(resume) },
      { heading: 'Skills', blocks: allSkills(resume.skills).length ? [{ type: 'paragraph', text: allSkills(resume.skills).join('  •  ') }] : [] },
      { heading: 'Licenses & Certifications', blocks: certificationItems(resume).length ? [{ type: 'bullets', items: certificationItems(resume) }] : [] },
      { heading: 'Projects', blocks: projectBlocks(resume) },
      { heading: 'Languages', blocks: languageItems(resume).length ? [{ type: 'bullets', items: languageItems(resume) }] : [] },
      { heading: 'Honors & Awards', blocks: list(resume.awards).length ? [{ type: 'bullets', items: list(resume.awards) }] : [] },
      { heading: 'Volunteering', blocks: list(resume.volunteering).length ? [{ type: 'bullets', items: list(resume.volunteering) }] : [] },
    ],
  };
}

/** Single-column, ATS-safe resume. */
export function resumeDocument(resume, { label } = {}) {
  const p = resume.personal || {};
  const skills = resume.skills || {};
  const skillLines = [
    ['Technical', skills.technical], ['Tools', skills.tools], ['Functional', skills.functional],
    ['Industry', skills.industry], ['Soft skills', skills.soft],
  ].filter(([, v]) => list(v).length).map(([k, v]) => ({ type: 'labelled', label: k, text: list(v).join(', ') }));

  return {
    title: `${p.name || 'Candidate'} — Resume${label ? ` (${label})` : ''}`,
    header: { name: p.name, lines: contactLines(p) },
    footerNote: '',
    sections: [
      { heading: 'Professional Summary', blocks: resume.summary ? [{ type: 'paragraph', text: resume.summary }] : [] },
      { heading: 'Skills', blocks: skillLines },
      { heading: 'Professional Experience', blocks: experienceBlocks(resume) },
      { heading: 'Projects', blocks: projectBlocks(resume) },
      { heading: 'Education', blocks: educationBlocks(resume) },
      { heading: 'Certifications', blocks: certificationItems(resume).length ? [{ type: 'bullets', items: certificationItems(resume) }] : [] },
      { heading: 'Languages', blocks: languageItems(resume).length ? [{ type: 'paragraph', text: languageItems(resume).join(', ') }] : [] },
    ],
  };
}

export function coverLetterDocument(letter, personal = {}) {
  const body = String(letter.content || '').trim();
  return {
    title: `Cover letter — ${[letter.jobTitle, letter.company].filter(Boolean).join(', ') || 'Application'}`,
    header: { name: personal.name, lines: [[personal.email, personal.phone, personal.location].filter(Boolean).join('  •  ')] },
    footerNote: '',
    sections: [{ heading: [letter.jobTitle, letter.company].filter(Boolean).join(' — ') || 'Cover letter', blocks: [{ type: 'paragraph', text: body }] }],
  };
}

export function interviewDocument(set, personal = {}) {
  const qs = list(set.questions);
  return {
    title: `Interview preparation — ${set.jobTitle || 'Target role'}`,
    header: {
      name: personal.name,
      lines: [`Top ${qs.length} interview questions & answers — ${[set.jobTitle, set.company].filter(Boolean).join(', ')}`],
    },
    footerNote: 'DutyLaunch practice questions based on your profile and job description — not actual or leaked employer questions.',
    sections: qs.map((q, i) => ({
      heading: `Question ${i + 1} · ${q.category || 'General'} · ${q.difficulty || ''}`.replace(/ · $/, ''),
      blocks: [
        { type: 'paragraph', text: q.question },
        q.whyRelevant && { type: 'labelled', label: 'Why it is asked', text: q.whyRelevant },
        q.interviewerExpects && { type: 'labelled', label: 'What the interviewer expects', text: q.interviewerExpects },
        q.sampleAnswer && { type: 'labelled', label: 'Sample answer', text: q.sampleAnswer },
        list(q.keyPoints).length && { type: 'bullets', items: list(q.keyPoints) },
        q.followUp && { type: 'labelled', label: 'Possible follow-up', text: q.followUp },
        list(q.placeholders).length && { type: 'labelled', label: 'Replace or confirm before using', text: list(q.placeholders).join('; ') },
      ].filter(Boolean),
    })),
  };
}

export function mockReportDocument(session, personal = {}) {
  const r = session.report || {};
  return {
    title: `Mock interview report — ${session.jobTitle || 'Practice'}`,
    header: { name: personal.name, lines: [`${session.interviewType || ''} practice interview · ${session.difficulty || ''} · ${new Date(session.completedAt || session.updatedAt || Date.now()).toDateString()}`] },
    footerNote: 'AI-generated practice feedback — not an employer evaluation.',
    sections: [
      { heading: 'Summary', blocks: [r.summary && { type: 'paragraph', text: r.summary }, typeof r.overallScore === 'number' && { type: 'labelled', label: 'Practice score', text: `${r.overallScore}/100 (practice assessment)` }].filter(Boolean) },
      { heading: 'Strengths', blocks: list(r.strengths).length ? [{ type: 'bullets', items: list(r.strengths) }] : [] },
      { heading: 'Areas to improve', blocks: list(r.improvements).length ? [{ type: 'bullets', items: list(r.improvements) }] : [] },
      { heading: 'Topics to revise', blocks: list(r.topicsToRevise).length ? [{ type: 'bullets', items: list(r.topicsToRevise) }] : [] },
      ...list(session.turns).filter((t) => t.answer).map((t, i) => ({
        heading: `Q${i + 1}${t.isFollowUp ? ' (follow-up)' : ''}`,
        blocks: [
          { type: 'paragraph', text: t.question },
          { type: 'labelled', label: 'Your answer', text: t.answer },
          t.feedback?.summary && { type: 'labelled', label: 'Feedback', text: t.feedback.summary },
          list(t.feedback?.missingPoints).length && { type: 'labelled', label: 'Missing points', text: list(t.feedback.missingPoints).join('; ') },
          t.feedback?.modelAnswer && { type: 'labelled', label: 'Model answer', text: t.feedback.modelAnswer },
        ].filter(Boolean),
      })),
      { heading: 'Recommended next steps', blocks: list(r.nextSteps).length ? [{ type: 'bullets', items: list(r.nextSteps) }] : [] },
    ],
  };
}
