/**
 * One renderer for every downloadable career document (profile PDF,
 * resume, cover letter, interview pack), in PDF and DOCX.
 *
 * Documents are described as plain data — never HTML — so nothing a model
 * or candidate writes can inject markup or script into a download:
 *
 *   {
 *     title, subject,
 *     header: { name, lines: [string] },       // lines: headline, contact…
 *     footerNote: string,                       // e.g. "Generated by DutyLaunch"
 *     sections: [{ heading, blocks: [
 *       { type: 'paragraph', text },
 *       { type: 'bullets', items: [string] },
 *       { type: 'entry', title, subtitle, meta, text, bullets },
 *       { type: 'labelled', label, text },      // "Why it's asked: …"
 *       { type: 'spacer' },
 *     ]}],
 *   }
 *
 * PDFs are written UNCOMPRESSED on purpose: the resume extractor DutyLaunch
 * uses (pdf-parse) cannot read some compressed pdfkit output, and
 * candidates do re-upload documents we generate.
 */

import PDFDocument from 'pdfkit';
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Footer, PageNumber, BorderStyle, LevelFormat,
} from 'docx';

/* The built-in PDF fonts only cover Windows-1252. Map the common extras
   and replace anything else, rather than printing garbage glyphs. */
const WINANSI_EXTRA = new Set('€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ');
export function pdfSafe(text = '') {
  return String(text)
    .replace(/₹/g, 'Rs. ')
    .replace(/[\u2010\u2011\u2012]/g, '-')
    .replace(/\u00a0/g, ' ')
    .replace(/[^\x09\x0a\x0d\x20-\x7e\xa0-\xff]/g, (ch) => (WINANSI_EXTRA.has(ch) ? ch : '?'));
}

const clean = (v) => String(v ?? '').replace(/\s+\n/g, '\n').trim();

/** Safe download filename, e.g. "Priya_Sharma_LinkedIn_Profile.pdf". */
export function safeFilename(...parts) {
  const base = parts
    .filter(Boolean)
    .join('_')
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/[\s-]+/g, '_')
    .slice(0, 80);
  return base || 'DutyLaunch_Document';
}

/* ------------------------------------------------------------------ *
 * PDF
 * ------------------------------------------------------------------ */

const PDF = {
  margin: 54,
  ink: '#111827',
  muted: '#4b5563',
  accent: '#0B1F48',
  rule: '#cbd5e1',
};

export function renderPdf(doc) {
  return new Promise((resolve, reject) => {
    const pdf = new PDFDocument({
      size: 'A4',
      margins: { top: PDF.margin, bottom: PDF.margin + 14, left: PDF.margin, right: PDF.margin },
      bufferPages: true,
      compress: false,
      info: { Title: pdfSafe(doc.title || 'Document'), Author: pdfSafe(doc.header?.name || ''), Subject: pdfSafe(doc.subject || ''), Creator: 'DutyLaunch' },
    });
    const chunks = [];
    pdf.on('data', (c) => chunks.push(c));
    pdf.on('end', () => resolve(Buffer.concat(chunks)));
    pdf.on('error', reject);

    const width = pdf.page.width - PDF.margin * 2;
    const bottom = () => pdf.page.height - pdf.page.margins.bottom;
    const ensure = (h) => {
      if (pdf.y + h > bottom()) pdf.addPage();
    };

    /* Header */
    if (doc.header?.name) {
      pdf.font('Helvetica-Bold').fontSize(22).fillColor(PDF.accent).text(pdfSafe(doc.header.name), { width });
    }
    (doc.header?.lines || []).filter(Boolean).forEach((line, i) => {
      pdf.font(i === 0 ? 'Helvetica-Bold' : 'Helvetica').fontSize(i === 0 ? 11.5 : 9.5).fillColor(i === 0 ? PDF.ink : PDF.muted).text(pdfSafe(line), { width });
    });
    pdf.moveDown(0.6);

    /* Sections */
    (doc.sections || []).forEach((section) => {
      const blocks = (section.blocks || []).filter(Boolean);
      if (!blocks.length) return;
      ensure(48);
      pdf.moveDown(0.5);
      pdf.font('Helvetica-Bold').fontSize(10.5).fillColor(PDF.accent).text(pdfSafe(section.heading).toUpperCase(), { width, characterSpacing: 0.8 });
      const y = pdf.y + 2;
      pdf.moveTo(PDF.margin, y).lineTo(PDF.margin + width, y).lineWidth(0.8).strokeColor(PDF.rule).stroke();
      pdf.y = y + 6;

      blocks.forEach((b) => {
        pdf.fillColor(PDF.ink);
        if (b.type === 'paragraph') {
          ensure(28);
          pdf.font('Helvetica').fontSize(10).text(pdfSafe(clean(b.text)), { width, lineGap: 2 });
          pdf.moveDown(0.4);
        } else if (b.type === 'bullets') {
          (b.items || []).filter(Boolean).forEach((item) => {
            ensure(16);
            pdf.font('Helvetica').fontSize(10).text(`•  ${pdfSafe(clean(item))}`, PDF.margin + 8, pdf.y, { width: width - 8, lineGap: 1.5, indent: 0 });
          });
          pdf.x = PDF.margin;
          pdf.moveDown(0.3);
        } else if (b.type === 'entry') {
          ensure(40);
          pdf.font('Helvetica-Bold').fontSize(10.5).text(pdfSafe(b.title || ''), { width, continued: false });
          const sub = [b.subtitle, b.meta].filter(Boolean).join('   |   ');
          if (sub) pdf.font('Helvetica').fontSize(9.5).fillColor(PDF.muted).text(pdfSafe(sub), { width });
          pdf.fillColor(PDF.ink);
          if (b.text) pdf.font('Helvetica').fontSize(10).text(pdfSafe(clean(b.text)), { width, lineGap: 2 });
          (b.bullets || []).filter(Boolean).forEach((item) => {
            ensure(16);
            pdf.font('Helvetica').fontSize(10).text(`•  ${pdfSafe(clean(item))}`, PDF.margin + 8, pdf.y, { width: width - 8, lineGap: 1.5 });
          });
          pdf.x = PDF.margin;
          pdf.moveDown(0.5);
        } else if (b.type === 'labelled') {
          ensure(24);
          pdf.font('Helvetica-Bold').fontSize(9.5).fillColor(PDF.muted).text(`${pdfSafe(b.label)}: `, { width, continued: true });
          pdf.font('Helvetica').fillColor(PDF.ink).text(pdfSafe(clean(b.text)), { lineGap: 1.5 });
          pdf.moveDown(0.25);
        } else if (b.type === 'spacer') {
          pdf.moveDown(0.6);
        }
      });
    });

    /* Footer on every page: note + page numbers */
    const range = pdf.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      pdf.switchToPage(i);
      // The footer sits inside the bottom margin; without lifting the margin
      // pdfkit treats it as overflow and appends a blank page per footer.
      const savedBottom = pdf.page.margins.bottom;
      pdf.page.margins.bottom = 0;
      const fy = pdf.page.height - PDF.margin + 6;
      pdf.font('Helvetica').fontSize(8).fillColor(PDF.muted);
      if (doc.footerNote) pdf.text(pdfSafe(doc.footerNote), PDF.margin, fy, { width: width - 70, lineBreak: false });
      pdf.text(`Page ${i + 1} of ${range.count}`, PDF.margin, fy, { width, align: 'right', lineBreak: false });
      pdf.page.margins.bottom = savedBottom;
    }
    pdf.end();
  });
}

/* ------------------------------------------------------------------ *
 * DOCX
 * ------------------------------------------------------------------ */

const run = (text, o = {}) => new TextRun({ text: String(text ?? ''), font: 'Calibri', size: o.size || 21, bold: o.bold, color: o.color, italics: o.italics });

export async function renderDocx(doc) {
  const children = [];
  if (doc.header?.name) {
    children.push(new Paragraph({ children: [run(doc.header.name, { size: 40, bold: true, color: '0B1F48' })], spacing: { after: 60 } }));
  }
  (doc.header?.lines || []).filter(Boolean).forEach((line, i) => {
    children.push(new Paragraph({ children: [run(line, { size: i === 0 ? 23 : 19, bold: i === 0, color: i === 0 ? '111827' : '4B5563' })], spacing: { after: 20 } }));
  });

  (doc.sections || []).forEach((section) => {
    const blocks = (section.blocks || []).filter(Boolean);
    if (!blocks.length) return;
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [run(String(section.heading || '').toUpperCase(), { size: 22, bold: true, color: '0B1F48' })],
        spacing: { before: 280, after: 100 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'CBD5E1', space: 2 } },
      })
    );
    blocks.forEach((b) => {
      if (b.type === 'paragraph') {
        clean(b.text).split(/\n{2,}/).forEach((para) => children.push(new Paragraph({ children: [run(para)], spacing: { after: 120 } })));
      } else if (b.type === 'bullets') {
        (b.items || []).filter(Boolean).forEach((item) => children.push(new Paragraph({ numbering: { reference: 'bullets', level: 0 }, children: [run(clean(item))] })));
      } else if (b.type === 'entry') {
        children.push(new Paragraph({ children: [run(b.title || '', { bold: true, size: 22 })], spacing: { before: 120 } }));
        const sub = [b.subtitle, b.meta].filter(Boolean).join('   |   ');
        if (sub) children.push(new Paragraph({ children: [run(sub, { size: 19, color: '4B5563' })] }));
        if (b.text) children.push(new Paragraph({ children: [run(clean(b.text))], spacing: { after: 60 } }));
        (b.bullets || []).filter(Boolean).forEach((item) => children.push(new Paragraph({ numbering: { reference: 'bullets', level: 0 }, children: [run(clean(item))] })));
      } else if (b.type === 'labelled') {
        children.push(new Paragraph({ children: [run(`${b.label}: `, { bold: true, color: '4B5563', size: 19 }), run(clean(b.text), { size: 20 })], spacing: { after: 60 } }));
      } else if (b.type === 'spacer') {
        children.push(new Paragraph({ children: [] }));
      }
    });
  });

  const document = new Document({
    creator: 'DutyLaunch',
    title: doc.title || 'Document',
    numbering: {
      config: [{ reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 360, hanging: 260 } } } }] }],
    },
    sections: [
      {
        properties: { page: { margin: { top: 1000, bottom: 1000, left: 1000, right: 1000 } } },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  run(doc.footerNote ? `${doc.footerNote}   ` : '', { size: 16, color: '6B7280' }),
                  new TextRun({ children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES], size: 16, color: '6B7280', font: 'Calibri' }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });
  return Packer.toBuffer(document);
}

export const MIME = {
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

/** Renders and sends a document as a download (or inline preview). */
export async function sendDocument(res, doc, { format = 'pdf', filename, inline = false } = {}) {
  const fmt = format === 'docx' ? 'docx' : 'pdf';
  const buffer = fmt === 'docx' ? await renderDocx(doc) : await renderPdf(doc);
  const name = `${safeFilename(filename || doc.title)}.${fmt}`;
  res.set('Content-Type', MIME[fmt]);
  res.set('Content-Length', String(buffer.length));
  res.set('Cache-Control', 'private, no-store');
  res.set('X-Content-Type-Options', 'nosniff');
  res.set('Content-Disposition', `${inline && fmt === 'pdf' ? 'inline' : 'attachment'}; filename="${name}"`);
  res.send(buffer);
}
